#! /bin/sh

### BEGIN INIT INFO
# Provides:          bootprogress
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    rmnologin
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Indicate that we're mid-bootup
# Description: Indicate that we're mid-bootup
### END INIT INFO

N=/etc/init.d/bootprogress

set -e

case "$1" in
  start)
	# Tell the user that we're working on things...
	if [ -d /home/pi/miab ]
	then
                aplay /home/pi/miab/booting.wav
                sleep 7
                aplay /home/pi/miab/progress.wav
	fi
	;;
  stop|reload|restart|force-reload|status)
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
