#! /bin/sh

# Tell the user that we're working on things...
if [ -d /home/pi/miab ]
then
        # Turn on the progress LEDs
        play /home/pi/miab/booting.wav
        sleep 1.5
	# Check which version of the hardware we're running on
	if [ -f /home/pi/miab/version.txt ]
	then
		# We're on a >=V1.0 hardware
        	echo 25 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio25/direction
        	echo 1 > /sys/class/gpio/gpio25/value
        	sleep 1.5
        	echo 10 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio10/direction
        	echo 1 > /sys/class/gpio/gpio10/value
        	sleep 1.5
        	echo 24 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio24/direction
        	echo 1 > /sys/class/gpio/gpio24/value
        	sleep 1.5
        	echo 23 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio23/direction
        	echo 1 > /sys/class/gpio/gpio23/value
        	sleep 1.5
        	echo 22 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio22/direction
        	echo 1 > /sys/class/gpio/gpio22/value
        	sleep 1
        	echo 27 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio27/direction
        	echo 1 > /sys/class/gpio/gpio27/value
	else
		# We're on pre-V1 hardware
        	echo 10 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio10/direction
        	echo 1 > /sys/class/gpio/gpio10/value
        	sleep 1.5
        	echo 23 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio23/direction
        	echo 1 > /sys/class/gpio/gpio23/value
        	sleep 2
        	echo 22 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio22/direction
        	echo 1 > /sys/class/gpio/gpio22/value
        	sleep 2
        	echo 27 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio27/direction
        	echo 1 > /sys/class/gpio/gpio27/value
        	sleep 2
        	echo 17 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio17/direction
        	echo 1 > /sys/class/gpio/gpio17/value
        	sleep 2
        	echo 25 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio25/direction
        	echo 1 > /sys/class/gpio/gpio25/value
	fi
fi
exit 0
