#! /bin/sh

# Function to turn our "x.y.z" version numbers into a single number so we can easily compare them
# NB: Only works for individual components up to 999
# To find out which version
#    version `cat /home/pi/miab/version.txt`
#    sw_version=$?
# Then use $sw_version for comparisons
version() {
	return `echo "$1" | awk -F. '{ printf("%03d%03d%03d\n", $1,$2,$3); }'`
}

# Tell the user that we're working on things...
if [ -d /home/pi/miab ]
then
        # Turn on the progress LEDs
	sleep 0.5 # Pause briefly to give the soundcard time to be ready (issue #87)
        play /home/pi/miab/booting.wav
        sleep 1.5
	# Check which version of the hardware we're running on
	if [ -f /home/pi/miab/version.txt ]
	then
		# We're on a >=V1.0 hardware
        	echo 7 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio7/direction
        	echo 1 > /sys/class/gpio/gpio7/value
        	sleep 1.5
        	echo 24 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio24/direction
        	echo 1 > /sys/class/gpio/gpio24/value
        	sleep 1.5
        	echo 23 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio23/direction
        	echo 1 > /sys/class/gpio/gpio23/value
        	sleep 1.5
        	echo 4 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio4/direction
        	echo 1 > /sys/class/gpio/gpio4/value
        	sleep 1.5
        	echo 22 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio22/direction
        	echo 1 > /sys/class/gpio/gpio22/value
        	sleep 1
        	echo 27 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio27/direction
        	echo 1 > /sys/class/gpio/gpio27/value
	else
		# We're on pre-V1 hardware
        	echo 10 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio10/direction
        	echo 1 > /sys/class/gpio/gpio10/value
        	sleep 1.5
        	echo 23 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio23/direction
        	echo 1 > /sys/class/gpio/gpio23/value
        	sleep 2
        	echo 22 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio22/direction
        	echo 1 > /sys/class/gpio/gpio22/value
        	sleep 2
        	echo 27 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio27/direction
        	echo 1 > /sys/class/gpio/gpio27/value
        	sleep 2
        	echo 17 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio17/direction
        	echo 1 > /sys/class/gpio/gpio17/value
        	sleep 2
        	echo 25 > /sys/class/gpio/export
        	echo out > /sys/class/gpio/gpio25/direction
        	echo 1 > /sys/class/gpio/gpio25/value
	fi
fi
exit 0
